import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getCurrentSession } from "@/actions/auth";
import Header2 from "./Component/layout/Header";
import { SanityLive } from "@/sanity/lib/live";

import HeaderCategorySelector from "./Component/layout/HeaderCategorySelector";
import Cart from "./Component/cart/Cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {

  const {user} = await getCurrentSession();
  
  return (
    <html lang="en">
       <body className={`${inter.className} antialiased !bg-white min-h-[125vh]`}>
      <Header2 
      user={user}
      categorySelector={<HeaderCategorySelector/>}
      />
        {children}
        <Cart/>
        <SanityLive/>
      </body>
    </html>
  );
}
export default RootLayout;
