import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getCurrentSession } from "@/actions/auth";
import Header2 from "./Component/layout/Header";
import { SanityLive } from "@/sanity/lib/live";

import HeaderCategorySelector from "./Component/layout/HeaderCategorySelector";
import Cart from "./Component/cart/Cart";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {

  const {user} = await getCurrentSession();
  
  return (
    <html lang="en">
       <body className={`${inter.className} antialiased !bg-white min-h-[125vh]`}>
      <Header2 
      user={user}
      categorySelector={<HeaderCategorySelector/>}
      />
      <Script
      src='https://cloud.umami.is/script.js'
      strategy='beforeInteractive'
     data-website-id='ab4c5ba3-56ff-4564-a4ad-badbf6197156'

      
      
      
      />



        {children}
        <Cart/>
        <SanityLive/>
      </body>
    </html>
  );
}
export default RootLayout;
