import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { getCurrentSession } from "@/actions/auth";
import Header2 from "./Component/layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  
  const {user} = await getCurrentSession();
  return (
    <html lang="en">
       <body className={`${inter.className} antialiased !bg-white min-h-[125vh]`}>
      <Header2 user={user}/>
        {children}
      </body>
    </html>
  );
}
export default RootLayout;
